import React from 'react'
import Footer from '@theme-original/Footer'
import SupportMyWork from '@site/src/components/SupportMyWork'

// Wraps the stock footer so the app block appears on every docs page rather
// than only on the pages generated from README.md (those are regenerated by
// scripts/sync-docs.mjs and cannot hold site-only content).
export default function FooterWrapper(props) {
  return (
    <>
      <SupportMyWork />
      <Footer {...props} />
    </>
  )
}
