import js from '@eslint/js'
import stylistic from '@stylistic/eslint-plugin'
import tseslint from 'typescript-eslint'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import importPlugin from 'eslint-plugin-import'

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/build/**',
      'example/**',
      '.eslintrc.js',
      'eslint.config.js',
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.recommendedTypeChecked,
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tseslint.parser,
      parserOptions: {
        project: './tsconfig.json',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        JSX: 'readonly',
        React: 'readonly',
        __DEV__: 'readonly',
        NodeJS: 'readonly',
      },
    },
    plugins: {
      '@stylistic': stylistic,
      '@typescript-eslint': tseslint.plugin,
      react,
      'react-hooks': reactHooks,
      import: importPlugin,
    },
    settings: {
      react: {
        version: 'detect',
      },
      'import/ignore': ['react-native'],
    },
    rules: {
      // TypeScript rules
      '@typescript-eslint/adjacent-overload-signatures': 'error',
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
      '@typescript-eslint/await-thenable': 'error',
      '@typescript-eslint/naming-convention': [
        'error',
        {
          selector: 'variable',
          format: ['camelCase', 'UPPER_CASE', 'PascalCase', 'snake_case'],
          filter: {
            regex: '[a-z]+((\\d)|([A-Z0-9][a-z0-9_]+))*([A-Z])?',
            match: false,
          },
          leadingUnderscore: 'allow',
          trailingUnderscore: 'forbid',
        },
        {
          selector: 'class',
          format: ['PascalCase'],
        },
        {
          selector: 'interface',
          format: ['PascalCase'],
        },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'warn',
      '@typescript-eslint/no-floating-promises': 'error',
      '@typescript-eslint/no-for-in-array': 'error',
      '@typescript-eslint/no-invalid-this': 'error',
      '@typescript-eslint/no-misused-new': 'error',
      '@typescript-eslint/triple-slash-reference': 'error',
      '@typescript-eslint/dot-notation': 'error',
      '@typescript-eslint/no-extraneous-class': 'error',
      '@typescript-eslint/no-unnecessary-qualifier': 'warn',
      '@typescript-eslint/no-unused-expressions': [
        'error',
        {
          allowShortCircuit: true,
          allowTernary: true,
        },
      ],
      '@typescript-eslint/prefer-for-of': 'error',
      '@typescript-eslint/promise-function-async': 'error',
      '@typescript-eslint/restrict-plus-operands': 'error',
      '@typescript-eslint/typedef': [
        'error',
        {
          parameter: true,
          propertyDeclaration: true,
        },
      ],
      '@typescript-eslint/type-annotation-spacing': 'error',
      '@typescript-eslint/no-unnecessary-condition': 'error',
      '@typescript-eslint/method-signature-style': ['error', 'method'],
      '@typescript-eslint/no-namespace': 'error',
      '@typescript-eslint/explicit-member-accessibility': [
        'error',
        {
          accessibility: 'explicit',
          ignoredMethodNames: [],
          overrides: {
            constructors: 'off',
            parameterProperties: 'off',
          },
        },
      ],
      '@typescript-eslint/member-ordering': [
        'error',
        {
          default: [
            'public-static-field',
            'protected-static-field',
            'private-static-field',
            'public-static-method',
            'protected-static-method',
            'private-static-method',
            'constructor',
            'public-abstract-field',
            'public-abstract-method',
            'protected-abstract-field',
            'protected-abstract-method',
            'public-field',
            'protected-field',
            'private-field',
            'public-method',
            'protected-method',
            'private-method',
          ],
        },
      ],

      // Core ESLint rules
      'no-sequences': 'error',
      'no-shadow-restricted-names': 'warn',
      curly: ['error', 'multi', 'consistent'],
      'guard-for-in': 'error',
      'no-extra-label': 'warn',
      'no-unused-labels': 'error',
      'no-label-var': 'warn',
      'no-labels': ['warn', { allowLoop: true, allowSwitch: false }],
      'new-parens': 'error',
      'no-caller': 'error',
      'no-bitwise': 'error',
      'no-cond-assign': 'error',
      'no-console': [
        'error',
        {
          allow: [
            'warn',
            'dir',
            'timeLog',
            'assert',
            'clear',
            'count',
            'countReset',
            'group',
            'groupEnd',
            'table',
            'dirxml',
            'groupCollapsed',
            'Console',
            'profile',
            'profileEnd',
            'timeStamp',
            'context',
          ],
        },
      ],
      'no-new-func': 'warn',
      'no-new-object': 'warn',
      'no-new-symbol': 'warn',
      'no-new-wrappers': 'error',
      'no-debugger': 'error',
      'no-duplicate-imports': 'error',
      'no-duplicate-case': 'error',
      'no-redeclare': 'error',
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-eval': 'error',
      'no-implied-eval': 'warn',
      'no-return-await': 'error',
      'no-template-curly-in-string': 'error',
      'no-irregular-whitespace': 'error',
      'no-param-reassign': 'error',
      'no-sparse-arrays': 'error',
      'no-fallthrough': 'error',
      'no-throw-literal': 'error',
      'no-this-before-super': 'warn',
      'no-undef': 'error',
      'no-undef-init': 'error',
      'no-unsafe-finally': 'error',
      'no-var': 'error',
      'prefer-const': 'error',
      'prefer-object-spread': 'error',
      radix: 'error',
      'default-case': 'error',
      eqeqeq: ['error', 'always'],
      'use-isnan': 'error',
      'no-unused-vars': ['error', { args: 'none', ignoreRestSiblings: true }],
      'consistent-return': 'error',
      'prefer-numeric-literals': 'error',
      'no-case-declarations': 'off',
      'no-extra-boolean-cast': 'off',
      'no-dupe-class-members': 'off',

      // Import plugin rules
      'import/first': 'error',
      'import/no-deprecated': 'error',
      'import/no-amd': 'error',
      'import/no-anonymous-default-export': 'warn',
      'import/no-webpack-loader-syntax': 'error',

      // React rules
      'react/jsx-key': 'error',
      'react/jsx-no-bind': 'off',
      'react/jsx-no-comment-textnodes': 'warn',
      'react/jsx-no-duplicate-props': 'warn',
      'react/jsx-no-target-blank': 'warn',
      'react/jsx-no-undef': 'error',
      'react/jsx-pascal-case': ['error', { allowAllCaps: true }],
      'react/jsx-uses-react': 'warn',
      'react/jsx-uses-vars': 'warn',
      'react/no-danger-with-children': 'warn',
      'react/no-direct-mutation-state': 'warn',
      'react/no-is-mounted': 'warn',
      'react/no-typos': 'error',
      'react/require-render-return': 'error',
      'react/self-closing-comp': 'error',
      'react/style-prop-object': 'error',
      'react/no-find-dom-node': 'off',

      // React Hooks rules
      'react-hooks/exhaustive-deps': 'warn',
      'react-hooks/rules-of-hooks': 'error',

      // Stylistic rules (formatting)
      '@stylistic/spaced-comment': [
        'error',
        'always',
        { exceptions: ['*'], markers: ['/'] },
      ],
      '@stylistic/eol-last': 'error',
      '@stylistic/indent': [
        'error',
        2,
        {
          CallExpression: { arguments: 'first' },
          FunctionDeclaration: { parameters: 'first' },
          FunctionExpression: { parameters: 'first' },
          SwitchCase: 1,
          VariableDeclarator: 1,
          ignoredNodes: ['TSTypeParameterInstantiation'],
        },
      ],
      '@stylistic/linebreak-style': ['error', 'unix'],
      '@stylistic/max-len': [
        'error',
        { code: 120, ignoreTemplateLiterals: true },
      ],
      '@stylistic/no-multiple-empty-lines': ['error', { max: 1 }],
      '@stylistic/no-trailing-spaces': 'error',
      '@stylistic/quote-props': ['error', 'as-needed', { unnecessary: false }],
      '@stylistic/quotes': ['error', 'single', { allowTemplateLiterals: true }],
      '@stylistic/jsx-quotes': ['error', 'prefer-double'],
      '@stylistic/brace-style': ['error', '1tbs'],
      '@stylistic/semi': ['error', 'never'],
      '@stylistic/member-delimiter-style': [
        'error',
        {
          multiline: { delimiter: 'semi', requireLast: true },
          singleline: { delimiter: 'semi', requireLast: false },
        },
      ],
      '@stylistic/space-before-function-paren': ['error', 'never'],
      '@stylistic/space-in-parens': ['off', 'never'],
      '@stylistic/comma-dangle': [
        'error',
        {
          arrays: 'always-multiline',
          objects: 'always-multiline',
          imports: 'always-multiline',
          exports: 'never',
          functions: 'never',
        },
      ],
      '@stylistic/object-curly-spacing': ['warn', 'always'],
      '@stylistic/jsx-curly-spacing': [
        'error',
        {
          attributes: { when: 'never' },
          children: { when: 'never' },
          allowMultiline: true,
        },
      ],
      '@stylistic/no-multi-spaces': 'error',
      '@stylistic/no-whitespace-before-property': 'warn',
      '@stylistic/space-before-blocks': 'error',
      '@stylistic/space-infix-ops': 'error',
      '@stylistic/space-unary-ops': 'error',
      '@stylistic/switch-colon-spacing': 'error',
      '@stylistic/template-curly-spacing': 'error',
      '@stylistic/template-tag-spacing': 'error',
      '@stylistic/yield-star-spacing': 'error',
      '@stylistic/array-bracket-spacing': 'error',
      '@stylistic/arrow-spacing': 'error',
      '@stylistic/block-spacing': 'error',
      '@stylistic/comma-spacing': 'error',
      '@stylistic/computed-property-spacing': 'error',
      '@stylistic/func-call-spacing': 'error',
      '@stylistic/generator-star-spacing': 'error',
      '@stylistic/key-spacing': 'error',
      '@stylistic/keyword-spacing': 'error',
      '@stylistic/no-mixed-spaces-and-tabs': 'error',
      '@stylistic/jsx-closing-tag-location': 'error',
      '@stylistic/jsx-closing-bracket-location': 'error',
    },
  }
)
