/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Pages are generated by scripts/sync-docs.mjs and ordered by their
  // sidebar_position frontmatter, so the sidebar can stay fully automatic.
  docs: [{ type: 'autogenerated', dirName: '.' }],
}

export default sidebars
